spring:
  application:
    name: spring-jpa-osiv
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console